version: '3.5'
services:
  broker_1:
    container_name: broker-1
    image: mqttnet-broker:b1
    build:
      context: ../src
      dockerfile: mqttnet.broker/Dockerfile
    networks:
      - mqttnet
    environment:
      - RedisConnection=redis_center:6379
    depends_on:
      - redis_center
  broker_2:
    container_name: broker-2
    image: mqttnet-broker:b2
    build:
      context: ../src
      dockerfile: mqttnet.broker/Dockerfile
    environment:
      - RedisConnection=redis_center:6379
    networks:
      - mqttnet
    depends_on:
      - redis_center
  publisher-1:
    container_name: publisher-1
    image: mqttnet-publisher:p1
    environment:
      - broker=broker_1
    build:
      context: ../src
      dockerfile: mqttnet.client.publisher/Dockerfile
    ports:
      - "7227:80"
    networks:
      - mqttnet
    depends_on:
      - broker_1
  publisher-2:
    container_name: publisher-2
    image: mqttnet-publisher:p2
    environment:
      - broker=broker_2
    build:
      context: ../src
      dockerfile: mqttnet.client.publisher/Dockerfile
    ports:
      - "7228:80"
    networks:
      - mqttnet
    depends_on:
      - broker_2
  redis_center:
    image: redis
    networks:
      - mqttnet
networks:
    mqttnet:
      driver: bridge